repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.3.3
    hooks:
    -   id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]
    -   id: ruff-format
        types: [ python ]

-   repo: local
    hooks:
    -   id: mypy
        name: mypy
        entry: poetry run mypy
        language: python
        types: [python]
        require_serial: true
        pass_filenames: true
        additional_dependencies: [.]
