# Generated by Django 4.2.9 on 2025-04-29 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0002_remove_profile_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweet",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="tweets", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
